### ISSUE TITLE
Users can scan their emails for keywords indicative of phishing

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#32]
As a user, I want the extension to scan my email bodies for specific keywords, so I can be warned if the email indicates any form of phishing.

## Tasks
- [x] Compile List of Keywords
- [x] Scan email for keywords
- [x] Compare to keywords in database
- [x] Develop report of keyword search (way for analysis algorithm to use)
