### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#47]
As a developer, I want to set up the scripts and workflows for github, so that the repository can be more streamlined automated.

## Tasks
- [x] A build.sh that builds all components of your project
- [x] A test.sh that runs all tests of your project
- [x] A github action that runs your build.sh and test.sh on every check-in or pull request
- [x] A status badge showing the status of your project
