### ISSUE TITLE
Setting up a database

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#48]
As a developer, I want a database to store information in, so that we can use that information to compare against scanned email data.

## Tasks
- [x] SQL Schema written and in directory
- [x] Database contains keywords commonly found in phishing emails
- [x] Database connects with extension
